### ISSUE TITLE
Large Playlist names makes the Song Title container very small and pushes it to the side

### ISSUE THREAD

**Issue by RadJeff7** [GentlyTech/who-added#1]
Hi, I recently started using the 'WhoAdded' Extension in spicetify & sincerely thank you for adding this. This helps me a lot as I have a lot of collaborative playlists.

But recently saw this issue with Playlists with very big names. 
![image](https://user-images.githubusercontent.com/53948620/231538332-665a731e-f0e0-4a6e-b20a-5bbd427cea89.png)

This makes the Song Title container very small. 

Can we add a `text-overflow: ellipsis` or similar to emphasized Playlist names to concatenate large playlist names. 
I do understand this is an extreme example but thought of creating one issue nonetheless.

**Comment by GentlyTech** [comment]
Hi, I'm glad you find my extension useful!

Thanks for bringing this to my attention. For now I have added a fixed width so that it won't agressively resize the song title/info container. I realize that some of the text will be cut off as a result, which is not ideal. I could add a scrollbar but it didn't look great when I tried, so I opted to just let it cut off for now. The plan is to hopefully at some point figure out how to do text panning (like Spotify does with their song info when it overflows).

Hopefully that's sufficient for now. Let me know about any further issues you may encounter/suggestions you may have!

Thanks!

**Comment by GentlyTech** [comment]
I have altered the (still temporary) fix and made it so that the song info has priority on sizing and just the extension will resize when the width becomes too small (since my last fix was kinda half assed, my apologies).

You may need to manually install it since GitHub seems to cache assets when served to the same IP (assuming you're using the marketplace).
